apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  type: LoadBalancer
  selector:
    app: heart-disease-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000