apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app: heart-disease-app
spec:
  type: LoadBalancer
  selector:
    app: heart-disease-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000